name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  test_with_pytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install pytest
        pip install -e .
    - name: Test with pytest
      run: |
        python -m pytest -vv tests/

  lint_with_flake8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with pylint
      run: |
        flake8 configen

  format_with_black_and_isort:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black isort
    - name: Format with black
      run: |
        python -m black --check configen
    - name: Format with isort
      run: |
        isort . --check --diff

  type_check_with_mypy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install mypy
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    - name: Type check with mypy
      run: |
        mypy --python-version 3.8 configen

  check_yaml:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pydocstyle
      run: |
        python -m pip install --upgrade pip
        pip install yamllint
    - name: Check docstrings with pydocstyle
      run: |
        yamllint .
